version: '3.7'
services:
  app:
    build:
      context: .
    environment:
      RAILS_LOG_TO_STDOUT: "true"
      RAILS_ENV: production
      RAILS_MAX_THREADS: 16
      WEB_CONCURRENCY: 2
    ports:
      - 5000:5000
    depends_on:
      - redis
    restart: always
    logging:
        driver: "json-file"
        options:
          max-size: "100k"
          max-file: "10"
  
  redis:
    image: redis:latest
    ports:
      - 6379
    restart: always
    logging:
        driver: "json-file"
        options:
          max-size: "100k"
          max-file: "10"
